/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo15.vistas;

import java.text.DecimalFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidadgrupo15.accesoADatos.AlumnoData;
import universidadgrupo15.accesoADatos.InscripcionData;
import universidadgrupo15.accesoADatos.MateriaData;
import universidadgrupo15.entidades.Alumno;
import universidadgrupo15.entidades.Inscripcion;
import universidadgrupo15.entidades.Materia;

/**
 *
 * @author Enzo Bulacio
 */
public class VistaNotas2CB extends javax.swing.JInternalFrame {
    MateriaData mateData = new MateriaData();
    AlumnoData aludata = new AlumnoData();
    InscripcionData idata = new InscripcionData();
    DefaultComboBoxModel  modeloCBAlumno = new DefaultComboBoxModel();
    DefaultComboBoxModel  modeloCBMateria = new DefaultComboBoxModel();
    DefaultTableModel modeloTabla = new DefaultTableModel() { @Override
     public boolean isCellEditable(int row, int column) {
          return column == 2;
	}
     };
    
    
    /**
     * Creates new form VistaInscripciones
     */
    public VistaNotas2CB() {
        initComponents();
        //crearEncabezadosTabla();
        cargarCBAlumnos();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jCBAlumno = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jBGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCBMateria = new javax.swing.JComboBox<>();
        jTFNota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Gestión de Incripciones");

        jCBAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAlumnoActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione un Alumno");

        jBGuardar.setText("Actualizar Calificacion");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccione una Materia");

        jCBMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBMateriaActionPerformed(evt);
            }
        });

        jTFNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNotaKeyTyped(evt);
            }
        });

        jLabel4.setText("Calificacion");

        jButton1.setText("Editar Nota");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jCBAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jTFNota, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(jButton1))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCBMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jBGuardar)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        guardar();
        jTFNota.setEnabled(false);
        jBGuardar.setEnabled(false);
        jButton1.setEnabled(true);
        cargarNota();
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jCBAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAlumnoActionPerformed
      jCBMateria.removeAllItems();
      cargarCBMaterias();
      //jCBMateria.requestFocus();
      
    }//GEN-LAST:event_jCBAlumnoActionPerformed

    private void jCBMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBMateriaActionPerformed
        jTFNota.setEnabled(false);
        jBGuardar.setEnabled(false);
        cargarNota();
    }//GEN-LAST:event_jCBMateriaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jTFNota.setEnabled(true);
       jTFNota.requestFocus();
       jBGuardar.setEnabled(true);
       jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTFNotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNotaKeyTyped
       
        
    }//GEN-LAST:event_jTFNotaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBAlumno;
    private javax.swing.JComboBox<String> jCBMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTFNota;
    // End of variables declaration//GEN-END:variables

    private void cargarCBAlumnos(){
        for (Alumno alu : idata.listaAlumnosConInscripcion()){
            modeloCBAlumno.addElement(alu);
        }
        
        jCBAlumno.setModel(modeloCBAlumno);
        jCBAlumno.setSelectedItem("");
    }

    
    private void cargarCBMaterias(){
        Alumno alu = (Alumno) jCBAlumno.getSelectedItem();
        
        modeloCBMateria.removeAllElements();
        
        for (Inscripcion insc :idata.obtenerInscripcionesPorAlumno(alu.getIdAlumno())){
            modeloCBMateria.addElement(insc.getMateria());
        }
        
        jCBMateria.setModel(modeloCBMateria);
        jCBMateria.setSelectedItem("");
    }
    
    private void cargarNota(){
        try{
            Alumno alu = (Alumno) jCBAlumno.getSelectedItem();
            Materia mate = (Materia) jCBMateria.getSelectedItem();
       
            Inscripcion insc = idata.buscarNotaPorAlumnoyMateria(alu, mate);
            jTFNota.setText(String.valueOf(insc.getNota()));
        }catch (NullPointerException npe) {
            return;
        }
       
    }
       
    private void guardar(){
        DecimalFormat df = new DecimalFormat("#.##");
        try{
        Alumno alu = (Alumno) jCBAlumno.getSelectedItem();
        Materia mate = (Materia) jCBMateria.getSelectedItem();
        double nota = Double.parseDouble(jTFNota.getText());
        nota = Double.parseDouble(df.format(nota));
        if (nota > 10 || nota < 0) {
             JOptionPane.showMessageDialog(this, "La nota debe estar enre 0.0 y 10.0");
             return;
        }
        idata.actualizarNota(nota, alu.getIdAlumno(), mate.getIdMateria());
        }catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Ingrese un valor válido para la nota. \n Use . para separar decimales");
        }
    }
    

}
