/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo15.vistas;

import javax.swing.JOptionPane;
import universidadgrupo15.accesoADatos.MateriaData;
import universidadgrupo15.entidades.Materia;

/**
 *
 * @author Franco
 */
public class VistaMateria extends javax.swing.JInternalFrame {
MateriaData matedata = new MateriaData();
    /**
     * Creates new form VistaMateria
     */
    public VistaMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAgregarMate = new javax.swing.JButton();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelCodigo1 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelNombre1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido1 = new javax.swing.JLabel();
        jTextFieldAnio = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jRadioButtonEstado = new javax.swing.JRadioButton();
        jButtonAgregarMate1 = new javax.swing.JButton();
        jButtonGuardarMate = new javax.swing.JButton();
        jButtonEliminarMate = new javax.swing.JButton();
        jButtonSalirMate = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();

        jButtonAgregarMate.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgregarMate.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jButtonAgregarMate.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAgregarMate.setText("Nuevo");
        jButtonAgregarMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarMateActionPerformed(evt);
            }
        });

        jLabelTitulo1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo1.setText("Formulario Materia");

        jLabelCodigo1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCodigo1.setText("Codigo:");

        jTextFieldCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });

        jLabelNombre1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombre1.setText("Nombre:");

        jTextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jLabelApellido1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApellido1.setText("Año:");

        jTextFieldAnio.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnioActionPerformed(evt);
            }
        });

        jLabelEstado.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEstado.setText("Estado:");

        jRadioButtonEstado.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N

        jButtonAgregarMate1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgregarMate1.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jButtonAgregarMate1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAgregarMate1.setText("Nuevo");
        jButtonAgregarMate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarMate1ActionPerformed(evt);
            }
        });

        jButtonGuardarMate.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGuardarMate.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jButtonGuardarMate.setForeground(new java.awt.Color(0, 0, 0));
        jButtonGuardarMate.setText("Guardar");
        jButtonGuardarMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarMateActionPerformed(evt);
            }
        });

        jButtonEliminarMate.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEliminarMate.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jButtonEliminarMate.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEliminarMate.setText("Eliminar");
        jButtonEliminarMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarMateActionPerformed(evt);
            }
        });

        jButtonSalirMate.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalirMate.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jButtonSalirMate.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalirMate.setText("Salir");

        jButtonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCodigo1)
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonEstado)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonEliminarMate))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                        .addComponent(jButtonBuscar)
                                        .addGap(55, 55, 55))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTitulo1)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonSalirMate)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAgregarMate1)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonGuardarMate))
                            .addComponent(jLabelEstado)
                            .addComponent(jLabelApellido1)
                            .addComponent(jLabelNombre1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo1)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre1)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido1)
                    .addComponent(jTextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEstado)
                    .addComponent(jRadioButtonEstado))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarMate1)
                    .addComponent(jButtonGuardarMate)
                    .addComponent(jButtonEliminarMate)
                    .addComponent(jButtonSalirMate))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnioActionPerformed

    private void jButtonAgregarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarMateActionPerformed
        // TODO add your handling code here:

        Materia mate = new Materia();

        mate.setAnio(Integer.parseInt(jTextFieldAnio.getText()));
        mate.setNombre(jTextFieldNombre.getText());
        mate.setEstado(jRadioButtonEstado.isSelected());

        try{
            matedata.AgregarMateria(mate);
        }catch(NullPointerException npe){

            JOptionPane.showMessageDialog(this, "Faltan datos para crear la materia");
        }
    }//GEN-LAST:event_jButtonAgregarMateActionPerformed

    private void jButtonAgregarMate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarMate1ActionPerformed
        // TODO add your handling code here:

        Materia mate = new Materia();

        mate.setAnio(Integer.parseInt(jTextFieldAnio.getText()));
        mate.setNombre(jTextFieldNombre.getText());
        mate.setEstado(jRadioButtonEstado.isSelected());

        try{
            matedata.AgregarMateria(mate);
        }catch(NullPointerException npe){

            JOptionPane.showMessageDialog(this, "Faltan datos para crear la materia");
        }
    }//GEN-LAST:event_jButtonAgregarMate1ActionPerformed

    private void jButtonGuardarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarMateActionPerformed
        // TODO add your handling code here:
        Materia mate = matedata.buscarMateriaPorID(Integer.parseInt(jTextFieldCodigo.getText()));
        mate.setAnio(Integer.parseInt(jTextFieldAnio.getText()));
        mate.setNombre(jTextFieldNombre.getText());

        matedata.modificarMateria(mate);
    }//GEN-LAST:event_jButtonGuardarMateActionPerformed

    private void jButtonEliminarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarMateActionPerformed
        // TODO add your handling code here:
        matedata.borrarMateria(Integer.parseInt(jTextFieldCodigo.getText()));
        jRadioButtonEstado.setSelected(false);
    }//GEN-LAST:event_jButtonEliminarMateActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:

        Materia materia = null;
        try{
            if (jTextFieldCodigo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un ID");

            }else{

                int id = Integer.parseInt(jTextFieldCodigo.getText());
                materia = matedata.buscarMateriaPorID(id);
            }

            jTextFieldCodigo.setText(String.valueOf(materia.getIdMateria()));
            jTextFieldAnio.setText(String.valueOf(materia.getAnio()));
            jTextFieldNombre.setText(String.valueOf(materia.getNombre()));
            jRadioButtonEstado.setSelected(materia.isEstado());
        }catch(NullPointerException n){
            JOptionPane.showMessageDialog(this, "Valor de ID invalido o inexistente");

        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarMate;
    private javax.swing.JButton jButtonAgregarMate1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminarMate;
    private javax.swing.JButton jButtonGuardarMate;
    private javax.swing.JButton jButtonSalirMate;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelCodigo1;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JRadioButton jRadioButtonEstado;
    private javax.swing.JTextField jTextFieldAnio;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
